## Data Analysis With python

### Working With Numpy Basics

In [62]:

print("helloWorld")
import numpy as np

helloWorld


In [6]:
list = [1,2,3,4,5,6,7,8]
print (type(list))
nparr = np.array(list)
print(type(nparr))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
# 1D Array
Arr1D = np.array([1,2,3,4,5])
print(Arr1D)
print(Arr1D.shape)

[1 2 3 4 5]
(5,)


In [12]:
# 2D Array
Arr2D = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(Arr2D)
print(Arr2D.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


#### Creating Arrays using In-Built Methods

In [21]:
a=np.arange(1,9)
print(a)
b=np.arange(1,9,2)
print(b)


[1 2 3 4 5 6 7 8]
[1 3 5 7]


In [22]:
# Reshaping
z = a.reshape(8,1)    # 8 Rows and 1 Column
print(z)
x = a.reshape(4,2)
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
np.ones((3,4))   #3 rows 4 columns  

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.eye(3)      # creates Identity matrices 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Numpy Vectorised Operations

In [27]:
arr11 = np.array([1,2,3,4,5,6,7])
arr22 = np.array([10,20,30,40,50,60,70])

#Addition
print("Addition = ", arr11+arr22)

#Substraction
print("Substraction = ", arr11-arr22)

#Multiplication
print("Multiplication = ", arr11*arr22)

#Division
print("Division = ", arr11/arr22)

Addition =  [11 22 33 44 55 66 77]
Substraction =  [ -9 -18 -27 -36 -45 -54 -63]
Multiplication =  [ 10  40  90 160 250 360 490]
Division =  [0.1 0.1 0.1 0.1 0.1 0.1 0.1]


#### Universal Function

In [29]:
UniArr = np.array([2,3,4,5,6])

print(np.sqrt(UniArr))
print(np.exp(UniArr))
print(np.sin(UniArr))
print(np.log(UniArr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


#### Array Slicing


In [55]:
ArrSlice = np.array([[2,3,4,5],[5,6,7,8],[9,10,11,12]])

print(ArrSlice)
print(ArrSlice[0])
print(ArrSlice[0][3])
print(ArrSlice[2][1:4])
print(ArrSlice[1:,2:])    #

[[ 2  3  4  5]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 3 4 5]
5
[10 11 12]
[[ 7  8]
 [11 12]]


#### Statistical Concepts

In [58]:
#Normalization 

data = np.array([1,2,3,4,5,6])

mean = np.mean(data)
print(mean)
stnd_dev = np.std(data)
print(stnd_dev)


Normalized_Data = (data-mean)/stnd_dev
print("Normalizated Data is :",Normalized_Data)

3.5
1.707825127659933
Normalization is : [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


#### Mean, Median, Variance, Standard-Deviation

In [ ]:
D1 = np.array([1,2,3,4,5])
print(np.mean(D1))
print(np.median(D1))
print(np.var(D1))
print(np.std(D1))